### ISSUE TITLE
Upgrade to Deeptools v3.5.3

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/Dockers#12]
@kopardev 
Deeptools [v3.5.3](https://github.com/deeptools/deepTools/releases/tag/3.5.3) which was released just yesterday [fixes a numpy deprecation error in the plotFingerprint command](https://github.com/deeptools/deepTools/blame/83f192947606c62028717f0e0824dc23a07536dc/deeptools/plotFingerprint.py#L244).

The error message which occurs in v3.5.2:

```sh
Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/plotFingerprint", line 12, in <module>
      main(args)
    File "/usr/local/lib/python3.8/dist-packages/deeptools/plotFingerprint.py", line 476, in main
      syntheticJSD = getSyntheticJSD(num_reads_per_bin[:, idx])
    File "/usr/local/lib/python3.8/dist-packages/deeptools/plotFingerprint.py", line 243, in getSyntheticJSD
      chip = np.zeros(MAXLEN, dtype=np.int)
    File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 305, in __getattr__
      raise AttributeError(__former_attrs__[attr])
  AttributeError: module 'numpy' has no attribute 'int'.
  `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
      https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

**Comment by kelly-sovacool** [comment]
fixed by [07f7a2d](https://github.com/CCBR/Dockers/commit/07f7a2de0e06494a4d3152f032c34be931d98246)
